### ISSUE TITLE
Scroll position reset everytime

### ISSUE THREAD

**Issue by kennyvoo** [vivien000/st-click-detector#1]
Can it stay at the clicked scroll position?

**Comment by vivien000** [comment]
Hi @kennyvoo. I'm not sure what you mean. Do you mean that for example, if you scrolled to the bottom of a page, if you click here on a link included in a st-click-detector component, you wouldn't like to go back to the top of the page?
If so, this is the behavior that I see, for example here: https://huggingface.co/spaces/vivien/semanticsearch (I go to the bottom of the page and I click on a "similar movies" link: in that situation, I stay at the bottom of the page with either Firefox or Chrome)

**Comment by kennyvoo** [comment]
Yes. This is what I meant. For my case, when i click on the image, it will reload and go to the top. This might due to the change of style of the image. When I click on my image, I'll modify the border of the image.

Thanks for answering my question. I've found a workaround to my problem.
