### ISSUE TITLE
Add play detect functionality to video 

### ISSUE THREAD

**Issue by Jiltseb** [vivien000/st-click-detector#5]
Awesome component! Thanks a lot!

I am curious to know if a similar functionality can be applied to videos (not the same functionality). I embedded videos and detected the clicks already. 
But what I want to achieve is to "get the moment when it started playing and stopped playing" based on the playing button. Similar functionality can be achieved in the front end by adding JS with requestVideoFrameCallback API. But is there a way to get it done in streamlit? This will ensure that I can show contextual content in sync with the video.

**Comment by vivien000** [comment]
Hi @Jiltseb. It definitely seems possible to create a Streamlit component for this, especially if you already know how to achieve this in Javascript. Frankly, I don't know much about Javascript and I still managed to create components. There are tutorials on this and you can ask for support through the Streamlit discussion forum if needed.
